version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq-order-maintainer
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  order-processor:
    image: order-processing-app
    container_name: order-processor
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - rabbitmq
      - prometheus
      - tempo
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      MANAGEMENT_TRACING_ENABLED: true
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0
      MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://tempo:4318/v1/traces"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOKI_DS_URL=http://loki:3100
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - tempo
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo/tempo.yml
    ports:
      - "4318:4318"
      - "3200:3200"
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
volumes:
  grafana-storage: